[prod_servers]
prod-web-01 ansible_host=10.0.1.10
prod-web-02 ansible_host=10.0.1.11
prod-db-01  ansible_host=10.0.1.20

[dev_servers]
dev-01 ansible_host=10.0.2.10
dev-02 ansible_host=10.0.2.11

[all:vars]
ansible_user=ansible
ansible_become=yes
